CREATE DATABASE AGENDA IF NOT EXISTS;

CREATE TABLE REGISTRO ( 
	ID VARCHAR( 100 ) NOT NULL,
	NOME VARCHAR( 100 ) NOT NULL,
	SOBRENOME VARCHAR( 100 ) NULL,
	APELIDO VARCHAR( 50 ) NULL,
	ANIVERSARIO DATE NULL,
	ENDERECO VARCHAR( 255 ) NULL,
PRIMARY KEY ( ID ) );
	
CREATE TABLE CONTATO ( 
	ID VARCHAR( 100 ) NOT NULL,
	TIPO INT( 1 ) NOT NULL,
	DESCRICAO VARCHAR( 60 ) NOT NULL,
	PREFERENCIAL INT( 1 ) NOT NULL,
	REGISTRO_ID VARCHAR( 100 ) NOT NULL,
PRIMARY KEY ( ID ) );
	
ALTER TABLE CONTATO
    ADD CONSTRAINT FK_REGISTRO_CONTATO_1 FOREIGN KEY ( REGISTRO_ID )
    REFERENCES REGISTRO( ID );
	
	
